package com.insurance.InsuranceApp.dto;
// src/main/java/com/example/policyapp/dto/PolicyDTO.java


import jakarta.validation.constraints.Future;
import jakarta.validation.constraints.FutureOrPresent;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;

/**
 * Data Transfer Object for Policy creation and response.
 * Used to transfer policy data between client and server,
 * providing validation for incoming requests.
 */
public class PolicyDTO {

    // Policy ID is auto-generated by the database, so not included in DTO for creation
    private Long policyId;

    @NotNull(message = "Policy end date cannot be null")
//    @Future(message = "Policy end date must be in the future")
    @FutureOrPresent
    private LocalDate policyEndDate;

    @NotNull(message = "Policy start date cannot be null")
//    @FutureOrPresent(message = "Policy start date must be in the present or future")
    @FutureOrPresent
    private LocalDate policyStartDate;

    @NotBlank(message = "Policy status cannot be blank")
    private String policyStatus; // e.g., "ACTIVE", "PENDING", "EXPIRED"

    @NotNull(message = "Premium amount cannot be null")
    @Positive(message = "Premium amount must be a positive value")
    private BigDecimal premiumAmount;

    @NotNull(message = "Plan ID cannot be null")
    @Positive(message = "Plan ID must be a positive value")
    private Long planId;

    @NotNull(message = "User ID cannot be null")
    @Positive(message = "User ID must be a positive value")
    private Long userId;
//
//    @NotNull(message = "Vehicle ID cannot be null")
//    @Positive(message = "Vehicle ID must be a positive value")
    private Long vehicleId;

    // Constructors
    public PolicyDTO() {
    }

    public PolicyDTO(Long policyId, LocalDate policyEndDate, LocalDate policyStartDate, String policyStatus,
                     BigDecimal premiumAmount, Long planId, Long userId, Long vehicleId) {
        this.policyId = policyId;
        this.policyEndDate = policyEndDate;
        this.policyStartDate = policyStartDate;
        this.policyStatus = policyStatus;
        this.premiumAmount = premiumAmount;
        this.planId = planId;
        this.userId = userId;
        this.vehicleId = vehicleId;
    }

    // Getters and Setters
    public Long getPolicyId() {
        return policyId;
    }

    public void setPolicyId(Long policyId) {
        this.policyId = policyId;
    }

    public LocalDate getPolicyEndDate() {
        return policyEndDate;
    }

    public void setPolicyEndDate(LocalDate policyEndDate) {
        this.policyEndDate = policyEndDate;
    }

    public LocalDate getPolicyStartDate() {
        return policyStartDate;
    }

    public void setPolicyStartDate(LocalDate policyStartDate) {
        this.policyStartDate = policyStartDate;
    }

    public String getPolicyStatus() {
        return policyStatus;
    }

    public void setPolicyStatus(String policyStatus) {
        this.policyStatus = policyStatus;
    }

    public BigDecimal getPremiumAmount() {
        return premiumAmount;
    }

    public void setPremiumAmount(BigDecimal premiumAmount) {
        this.premiumAmount = premiumAmount;
    }

    public Long getPlanId() {
        return planId;
    }

    public void setPlanId(Long planId) {
        this.planId = planId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getVehicleId() {
        return vehicleId;
    }

    public void setVehicleId(Long vehicleId) {
        this.vehicleId = vehicleId;
    }

    @Override
    public String toString() {
        return "PolicyDTO{" +
                "policyId=" + policyId +
                ", policyEndDate=" + policyEndDate +
                ", policyStartDate=" + policyStartDate +
                ", policyStatus='" + policyStatus + '\'' +
                ", premiumAmount=" + premiumAmount +
                ", planId=" + planId +
                ", userId=" + userId +
                ", vehicleId=" + vehicleId +
                '}';
    }
}
